"""打包脚本：将 AI Provider 打包为单文件 .exe（Windows）。

用法（在项目根目录下执行）::

    python build_exe.py

前置条件：Python 3.10+，Node.js 18+（用于前端构建）。
"""
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WEB = ROOT / "web"
NAME = "AIProvider"
DIST = ROOT / "dist"


def build_frontend():
    """构建前端到 web/dist。

    若构建失败（例如在 WSL 中 rollup 缺少平台原生模块），只要已有
    ``web/dist`` 就继续使用现有产物，绝不因构建失败清空 dist。
    """
    print(">>> 构建前端...")
    dist_dir = WEB / "dist"
    try:
        subprocess.run(["npm", "run", "build"], cwd=str(WEB), check=True)
        print("    前端构建完成。")
    except Exception as exc:
        if dist_dir.exists():
            print(f"    ⚠ 前端构建失败（{exc}），沿用已有 dist 产物。")
        else:
            print(f"    前端构建失败且无现有 dist，中止：{exc}")
            sys.exit(1)


def ensure_pyinstaller():
    """确保 PyInstaller 已安装。"""
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print(">>> 安装 PyInstaller...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "pyinstaller"],
            check=True, capture_output=True,
        )
        print("    PyInstaller 安装完成。")


def read_base_version():
    """从 main.py 读取基础语义版本（唯一事实来源）。"""
    text = (ROOT / "main.py").read_text(encoding="utf-8")
    m = re.search(r'^VERSION\s*=\s*["\']([\d.]+)["\']', text, re.MULTILINE)
    return m.group(1) if m else "0.0.0"


def parse_version_parts(version):
    """'0.2.0' -> [0, 2, 0]（至少补齐到 3 段）。"""
    parts = [int(x) for x in version.split(".") if x != ""]
    while len(parts) < 3:
        parts.append(0)
    return parts[:3]


def get_build_number():
    """构建号 = 当前分支的 git 提交总数；每次提交并打包都会递增。"""
    try:
        out = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            cwd=str(ROOT), capture_output=True, text=True, check=True,
        )
        return int(out.stdout.strip())
    except Exception:
        return 0


def write_version_artifacts(version_str, version_tuple):
    """生成 _version.py 与 version_info.txt（覆盖式，勿手改）。"""
    (ROOT / "_version.py").write_text(
        "# Generated by build_exe.py — do not edit.\n"
        f"__build__ = {version_tuple[3]}\n"
        f'__version__ = "{version_str}"\n',
        encoding="utf-8",
    )

    version_info = f'''# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'AIProvider'),
         StringStruct(u'FileDescription', u'AIProvider'),
         StringStruct(u'FileVersion', u'{version_str}'),
         StringStruct(u'InternalName', u'AIProvider'),
         StringStruct(u'LegalCopyright', u''),
         StringStruct(u'OriginalFilename', u'AIProvider.exe'),
         StringStruct(u'ProductName', u'AIProvider'),
         StringStruct(u'ProductVersion', u'{version_str}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''
    (ROOT / "version_info.txt").write_text(version_info, encoding="utf-8")


def build_exe():
    """执行 PyInstaller 打包。"""
    print(">>> PyInstaller 打包中...")

    # 自动生成版本：基础语义版本（main.py） + git 提交数作为构建号。
    base = read_base_version()
    major, minor, patch = parse_version_parts(base)
    build = get_build_number()
    version_tuple = (major, minor, patch, build)
    version_str = f"{major}.{minor}.{patch}.{build}"
    write_version_artifacts(version_str, version_tuple)
    print(f">>> 版本: {version_str}  (基础 {base} + 构建号 {build})")

    dist_dir = DIST
    if dist_dir.exists():
        print("    清理旧 dist...")
        shutil.rmtree(dist_dir)

    sep = ";" if sys.platform == "win32" else ":"
    add_data_web = f"{WEB / 'dist'}{sep}web/dist"
    add_data_migrations = f"{ROOT / 'core' / 'migrations' / 'migrations'}{sep}core/migrations/migrations"
    add_data_favicon = f"{WEB / 'favicon.ico'}{sep}web"

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--name", NAME,
        "--noconsole",
        "--icon", str(WEB / "favicon.ico"),
        "--version-file", str(ROOT / "version_info.txt"),
        "--add-data", add_data_web,
        "--add-data", add_data_migrations,
        "--add-data", add_data_favicon,
        "--collect-all", "uvicorn",
        "--collect-all", "pywin32",
        "--collect-all", "win32com",
        "--collect-submodules", "core.migrations.migrations",
        "--hidden-import", "main",
        "--hidden-import", "multiprocessing",
        "--hidden-import", "win32gui",
        "--hidden-import", "win32api",
        "--hidden-import", "win32con",
        "--hidden-import", "yaml",
        "--hidden-import", "_version",
        str(ROOT / "run.py"),
    ]

    start = time.time()
    subprocess.run(cmd, cwd=str(ROOT), check=True)
    elapsed = time.time() - start

    exe_path = DIST / f"{NAME}.exe"
    size_mb = exe_path.stat().st_size / (1024 * 1024) if exe_path.exists() else 0

    print()
    print("=" * 52)
    print("  ✅ 打包完成！")
    print(f"  输出文件: {exe_path}")
    print(f"  文件大小: {size_mb:.1f} MB")
    print(f"  耗时: {elapsed:.0f}s")
    print("=" * 52)
    print()
    print("  使用方法：")
    print(f"    1. 将 {NAME}.exe 复制到目标电脑")
    print("    2. 双击运行（首次启动自动创建 data/ 目录）")
    print("    3. 程序运行在系统托盘，右键图标可打开后台或退出")
    print(f"    4. 浏览器自动打开 http://localhost:8000")
    print()


def main():
    build_frontend()
    ensure_pyinstaller()
    build_exe()


if __name__ == "__main__":
    main()