"""Migration 022: add error_source to request_logs.

Distinguishes where an error originated:
  - "" (empty / None): upstream supplier response (upstream returned the status code)
  - "upstream": explicit upstream error
  - "circuit_open": error caused by the circuit breaker rejecting the request
  - "rate_limit": rate-limit/quota rejection (strategy, not upstream)
  - "internal": generated by this service itself (not an upstream response)
"""

import sqlite3
from core.migrations.base import Migration
from core.migrations.registry import register


@register
class Migration022(Migration):
    version = 22
    description = "Add error_source to request_logs for upstream vs strategy distinction"

    def up(self, conn):
        cols = [r["name"] for r in conn.execute("PRAGMA table_info(request_logs)")]
        if "error_source" not in cols:
            conn.execute("ALTER TABLE request_logs ADD COLUMN error_source TEXT")

    def down(self, conn):
        pass  # DROP COLUMN not supported by sqlite; leave it
